_BASE_: [
  '../datasets/coco_detection_LLVIP.yml',
  '../runtime_llvip.yml',
  '_base_/optimizer.yml',
  '_base_/damsdet_r50vd_1024.yml',
  '_base_/damsdet_reader_1024.yml',
]

find_unused_parameters: True
log_iter: 200
