_BASE_: [
  '../datasets/coco_detection_m3fd.yml',
  '../runtime_m3fd.yml',
  '_base_/optimizer.yml',
  '_base_/damsdet_r50vd.yml',
  '_base_/damsdet_reader.yml',
]

find_unused_parameters: True
log_iter: 200
